version: '3.8'

services:
  apollo-router:
    container_name: apollo-router
    image: ghcr.io/apollographql/router:v1.25.0
    ports:
      - "4000:4000"
  app:
    container_name: ${APP_CONTAINER_NAME}
    build: 
      context: .
      dockerfile: ./docker/golang/Dockerfile
    volumes: 
      - ./app:/go/src/app
    tty: true 
    depends_on:
      - db
    ports:
      - ${APP_PORT}:8080
    networks:
      - athena-network
  db:
    container_name: ${PSQL_HOST}
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      - POSTGRES_DB=${PSQL_DBNAME}
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_PASSWORD=${PSQL_PASS}
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d 
    ports:
      - ${PSQL_PORT}:5432
    networks:
      - athena-network
volumes:
  db-store:
networks:
  athena-network:
    external: true