version: '3.8'

services:
  app:
    container_name: ${APP_CONTAINER_NAME}
    build: 
      context: .
      dockerfile: ./docker/golang/Dockerfile
    volumes: 
      - ./app:/go/src/app
    tty: true 
    depends_on:
      - db
    ports:
      - ${APP_PORT}:3000
  db:
    container_name: ${DB_HOST}
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./app/database/init:/docker-entrypoint-initdb.d 
    ports:
      - ${DB_PORT}:5432

volumes:
  db-store: