version: '3'

tasks:
  setup:
    cmds:
      - docker-compose build --no-cache && docker-compose up -d
  gqlgen-generate:
    cmds:
      - cd ./app && go run ./cmd/gqlgen_generate.go
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true