version: '3'

dotenv: ['.env']


tasks:
  setup:
    cmds:
      - docker-compose build --no-cache && docker-compose up -d
  schema-gen:
    cmds:
      - cd ./app && go run ./cmd/gqlgen_generate.go
  migration-up:
    cmds:
      - migrate --path db/migrations --database postgres://$PSQL_USER:$PSQL_PASS@localhost:5432/$PSQL_DBNAME?sslmode=disable -verbose up
  migration-down:
    cmds:
      - migrate --path db/migrations --database postgres://$PSQL_USER:$PSQL_PASS@localhost:5432/$PSQL_DBNAME?sslmode=disable -verbose down
  migrate-force:
    comds:
      - migrate --path db/migrations --database postgres://$PSQL_USER:$PSQL_PASS@localhost:5432/$PSQL_DBNAME?sslmode=disable -verbose force 1
  create-db-schema:
    cmds:
      - docker run -v "$PWD/db/schema:/output" --net="host" schemaspy/schemaspy:latest -t pgsql \\ -host localhost:5432 -db $PSQL_DBNAME -u $PSQL_USER -p $PSQL_PASS -connprops useSSL\\\\=false -all
  open-schema:
    cmds:
      - open -a "Google Chrome" $PWD/db/schema/index.html