package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"log"
	"my_gql_server/graph/model"
	"my_gql_server/graph/validation"
	models "my_gql_server/my_models"

	"my_gql_server/infrastructures/repositories"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*models.Todo, error) {
	if err := validation.Handler(input); err != nil {
		return nil, err
	}
	log.Print("run exec create todo")

	todo, err := repositories.InsertTodo(ctx, input)

	if err != nil {
		return nil, err
	}

	return todo, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*models.User, error) {
	if err := validation.Handler(input); err != nil {
		return nil, err
	}
	return nil, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
