package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"fmt"
	"log"
	"my_gql_server/graph/model"
	"my_gql_server/my_models"
)

// User is the resolver for the user field.
func (r *itemResolver) User(ctx context.Context, obj *model.Item) (*models.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// User is the resolver for the user field.
func (r *todoResolver) User(ctx context.Context, obj *models.Todo) (*models.User, error) {
	log.Printf("user %s", obj.R.User.Email)
	return obj.R.User, nil
}

// Item returns ItemResolver implementation.
func (r *Resolver) Item() ItemResolver { return &itemResolver{r} }

// Todo returns TodoResolver implementation.
func (r *Resolver) Todo() TodoResolver { return &todoResolver{r} }

type itemResolver struct{ *Resolver }
type todoResolver struct{ *Resolver }
