// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AccountTypes                 string
	Accounts                     string
	Articles                     string
	Categories                   string
	Items                        string
	MaximumMonthlyTargetPayments string
	PaymentTypes                 string
	Payments                     string
	SchemaMigrations             string
	Statuses                     string
	Todos                        string
	Transactions                 string
	Users                        string
}{
	AccountTypes:                 "account_types",
	Accounts:                     "accounts",
	Articles:                     "articles",
	Categories:                   "categories",
	Items:                        "items",
	MaximumMonthlyTargetPayments: "maximum_monthly_target_payments",
	PaymentTypes:                 "payment_types",
	Payments:                     "payments",
	SchemaMigrations:             "schema_migrations",
	Statuses:                     "statuses",
	Todos:                        "todos",
	Transactions:                 "transactions",
	Users:                        "users",
}
