// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/v4/types"
	"github.com/volatiletech/strmangle"
)

// PredictCost is an object representing the database table.
type PredictCost struct {
	ID           int           `boil:"id" json:"id" toml:"id" yaml:"id"`
	CategoryName string        `boil:"category_name" json:"category_name" toml:"category_name" yaml:"category_name"`
	Label        string        `boil:"label" json:"label" toml:"label" yaml:"label"`
	CreatedAt    time.Time     `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt    time.Time     `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	Amount       types.Decimal `boil:"amount" json:"amount" toml:"amount" yaml:"amount"`

	R *predictCostR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L predictCostL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PredictCostColumns = struct {
	ID           string
	CategoryName string
	Label        string
	CreatedAt    string
	UpdatedAt    string
	Amount       string
}{
	ID:           "id",
	CategoryName: "category_name",
	Label:        "label",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
	Amount:       "amount",
}

var PredictCostTableColumns = struct {
	ID           string
	CategoryName string
	Label        string
	CreatedAt    string
	UpdatedAt    string
	Amount       string
}{
	ID:           "predict_costs.id",
	CategoryName: "predict_costs.category_name",
	Label:        "predict_costs.label",
	CreatedAt:    "predict_costs.created_at",
	UpdatedAt:    "predict_costs.updated_at",
	Amount:       "predict_costs.amount",
}

// Generated where

var PredictCostWhere = struct {
	ID           whereHelperint
	CategoryName whereHelperstring
	Label        whereHelperstring
	CreatedAt    whereHelpertime_Time
	UpdatedAt    whereHelpertime_Time
	Amount       whereHelpertypes_Decimal
}{
	ID:           whereHelperint{field: "\"predict_costs\".\"id\""},
	CategoryName: whereHelperstring{field: "\"predict_costs\".\"category_name\""},
	Label:        whereHelperstring{field: "\"predict_costs\".\"label\""},
	CreatedAt:    whereHelpertime_Time{field: "\"predict_costs\".\"created_at\""},
	UpdatedAt:    whereHelpertime_Time{field: "\"predict_costs\".\"updated_at\""},
	Amount:       whereHelpertypes_Decimal{field: "\"predict_costs\".\"amount\""},
}

// PredictCostRels is where relationship names are stored.
var PredictCostRels = struct {
	CategoryNameCategory string
}{
	CategoryNameCategory: "CategoryNameCategory",
}

// predictCostR is where relationships are stored.
type predictCostR struct {
	CategoryNameCategory *Category `boil:"CategoryNameCategory" json:"CategoryNameCategory" toml:"CategoryNameCategory" yaml:"CategoryNameCategory"`
}

// NewStruct creates a new relationship struct
func (*predictCostR) NewStruct() *predictCostR {
	return &predictCostR{}
}

func (r *predictCostR) GetCategoryNameCategory() *Category {
	if r == nil {
		return nil
	}
	return r.CategoryNameCategory
}

// predictCostL is where Load methods for each relationship are stored.
type predictCostL struct{}

var (
	predictCostAllColumns            = []string{"id", "category_name", "label", "created_at", "updated_at", "amount"}
	predictCostColumnsWithoutDefault = []string{"category_name", "label", "created_at", "updated_at", "amount"}
	predictCostColumnsWithDefault    = []string{"id"}
	predictCostPrimaryKeyColumns     = []string{"id"}
	predictCostGeneratedColumns      = []string{}
)

type (
	// PredictCostSlice is an alias for a slice of pointers to PredictCost.
	// This should almost always be used instead of []PredictCost.
	PredictCostSlice []*PredictCost
	// PredictCostHook is the signature for custom PredictCost hook methods
	PredictCostHook func(context.Context, boil.ContextExecutor, *PredictCost) error

	predictCostQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	predictCostType                 = reflect.TypeOf(&PredictCost{})
	predictCostMapping              = queries.MakeStructMapping(predictCostType)
	predictCostPrimaryKeyMapping, _ = queries.BindMapping(predictCostType, predictCostMapping, predictCostPrimaryKeyColumns)
	predictCostInsertCacheMut       sync.RWMutex
	predictCostInsertCache          = make(map[string]insertCache)
	predictCostUpdateCacheMut       sync.RWMutex
	predictCostUpdateCache          = make(map[string]updateCache)
	predictCostUpsertCacheMut       sync.RWMutex
	predictCostUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var predictCostAfterSelectHooks []PredictCostHook

var predictCostBeforeInsertHooks []PredictCostHook
var predictCostAfterInsertHooks []PredictCostHook

var predictCostBeforeUpdateHooks []PredictCostHook
var predictCostAfterUpdateHooks []PredictCostHook

var predictCostBeforeDeleteHooks []PredictCostHook
var predictCostAfterDeleteHooks []PredictCostHook

var predictCostBeforeUpsertHooks []PredictCostHook
var predictCostAfterUpsertHooks []PredictCostHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PredictCost) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range predictCostAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PredictCost) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range predictCostBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PredictCost) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range predictCostAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *PredictCost) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range predictCostBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *PredictCost) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range predictCostAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *PredictCost) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range predictCostBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *PredictCost) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range predictCostAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PredictCost) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range predictCostBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PredictCost) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range predictCostAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPredictCostHook registers your hook function for all future operations.
func AddPredictCostHook(hookPoint boil.HookPoint, predictCostHook PredictCostHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		predictCostAfterSelectHooks = append(predictCostAfterSelectHooks, predictCostHook)
	case boil.BeforeInsertHook:
		predictCostBeforeInsertHooks = append(predictCostBeforeInsertHooks, predictCostHook)
	case boil.AfterInsertHook:
		predictCostAfterInsertHooks = append(predictCostAfterInsertHooks, predictCostHook)
	case boil.BeforeUpdateHook:
		predictCostBeforeUpdateHooks = append(predictCostBeforeUpdateHooks, predictCostHook)
	case boil.AfterUpdateHook:
		predictCostAfterUpdateHooks = append(predictCostAfterUpdateHooks, predictCostHook)
	case boil.BeforeDeleteHook:
		predictCostBeforeDeleteHooks = append(predictCostBeforeDeleteHooks, predictCostHook)
	case boil.AfterDeleteHook:
		predictCostAfterDeleteHooks = append(predictCostAfterDeleteHooks, predictCostHook)
	case boil.BeforeUpsertHook:
		predictCostBeforeUpsertHooks = append(predictCostBeforeUpsertHooks, predictCostHook)
	case boil.AfterUpsertHook:
		predictCostAfterUpsertHooks = append(predictCostAfterUpsertHooks, predictCostHook)
	}
}

// OneG returns a single predictCost record from the query using the global executor.
func (q predictCostQuery) OneG(ctx context.Context) (*PredictCost, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single predictCost record from the query.
func (q predictCostQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PredictCost, error) {
	o := &PredictCost{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for predict_costs")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all PredictCost records from the query using the global executor.
func (q predictCostQuery) AllG(ctx context.Context) (PredictCostSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all PredictCost records from the query.
func (q predictCostQuery) All(ctx context.Context, exec boil.ContextExecutor) (PredictCostSlice, error) {
	var o []*PredictCost

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to PredictCost slice")
	}

	if len(predictCostAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all PredictCost records in the query using the global executor
func (q predictCostQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all PredictCost records in the query.
func (q predictCostQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count predict_costs rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q predictCostQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q predictCostQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if predict_costs exists")
	}

	return count > 0, nil
}

// CategoryNameCategory pointed to by the foreign key.
func (o *PredictCost) CategoryNameCategory(mods ...qm.QueryMod) categoryQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"classification\" = ?", o.CategoryName),
	}

	queryMods = append(queryMods, mods...)

	return Categories(queryMods...)
}

// LoadCategoryNameCategory allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (predictCostL) LoadCategoryNameCategory(ctx context.Context, e boil.ContextExecutor, singular bool, maybePredictCost interface{}, mods queries.Applicator) error {
	var slice []*PredictCost
	var object *PredictCost

	if singular {
		var ok bool
		object, ok = maybePredictCost.(*PredictCost)
		if !ok {
			object = new(PredictCost)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePredictCost)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePredictCost))
			}
		}
	} else {
		s, ok := maybePredictCost.(*[]*PredictCost)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePredictCost)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePredictCost))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &predictCostR{}
		}
		args = append(args, object.CategoryName)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &predictCostR{}
			}

			for _, a := range args {
				if a == obj.CategoryName {
					continue Outer
				}
			}

			args = append(args, obj.CategoryName)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`categories`),
		qm.WhereIn(`categories.classification in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Category")
	}

	var resultSlice []*Category
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Category")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for categories")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for categories")
	}

	if len(categoryAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.CategoryNameCategory = foreign
		if foreign.R == nil {
			foreign.R = &categoryR{}
		}
		foreign.R.CategoryNamePredictCosts = append(foreign.R.CategoryNamePredictCosts, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CategoryName == foreign.Classification {
				local.R.CategoryNameCategory = foreign
				if foreign.R == nil {
					foreign.R = &categoryR{}
				}
				foreign.R.CategoryNamePredictCosts = append(foreign.R.CategoryNamePredictCosts, local)
				break
			}
		}
	}

	return nil
}

// SetCategoryNameCategoryG of the predictCost to the related item.
// Sets o.R.CategoryNameCategory to related.
// Adds o to related.R.CategoryNamePredictCosts.
// Uses the global database handle.
func (o *PredictCost) SetCategoryNameCategoryG(ctx context.Context, insert bool, related *Category) error {
	return o.SetCategoryNameCategory(ctx, boil.GetContextDB(), insert, related)
}

// SetCategoryNameCategory of the predictCost to the related item.
// Sets o.R.CategoryNameCategory to related.
// Adds o to related.R.CategoryNamePredictCosts.
func (o *PredictCost) SetCategoryNameCategory(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Category) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"predict_costs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"category_name"}),
		strmangle.WhereClause("\"", "\"", 2, predictCostPrimaryKeyColumns),
	)
	values := []interface{}{related.Classification, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CategoryName = related.Classification
	if o.R == nil {
		o.R = &predictCostR{
			CategoryNameCategory: related,
		}
	} else {
		o.R.CategoryNameCategory = related
	}

	if related.R == nil {
		related.R = &categoryR{
			CategoryNamePredictCosts: PredictCostSlice{o},
		}
	} else {
		related.R.CategoryNamePredictCosts = append(related.R.CategoryNamePredictCosts, o)
	}

	return nil
}

// PredictCosts retrieves all the records using an executor.
func PredictCosts(mods ...qm.QueryMod) predictCostQuery {
	mods = append(mods, qm.From("\"predict_costs\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"predict_costs\".*"})
	}

	return predictCostQuery{q}
}

// FindPredictCostG retrieves a single record by ID.
func FindPredictCostG(ctx context.Context, iD int, selectCols ...string) (*PredictCost, error) {
	return FindPredictCost(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindPredictCost retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPredictCost(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*PredictCost, error) {
	predictCostObj := &PredictCost{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"predict_costs\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, predictCostObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from predict_costs")
	}

	if err = predictCostObj.doAfterSelectHooks(ctx, exec); err != nil {
		return predictCostObj, err
	}

	return predictCostObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *PredictCost) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PredictCost) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no predict_costs provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(predictCostColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	predictCostInsertCacheMut.RLock()
	cache, cached := predictCostInsertCache[key]
	predictCostInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			predictCostAllColumns,
			predictCostColumnsWithDefault,
			predictCostColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(predictCostType, predictCostMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(predictCostType, predictCostMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"predict_costs\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"predict_costs\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into predict_costs")
	}

	if !cached {
		predictCostInsertCacheMut.Lock()
		predictCostInsertCache[key] = cache
		predictCostInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single PredictCost record using the global executor.
// See Update for more documentation.
func (o *PredictCost) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the PredictCost.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PredictCost) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	predictCostUpdateCacheMut.RLock()
	cache, cached := predictCostUpdateCache[key]
	predictCostUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			predictCostAllColumns,
			predictCostPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update predict_costs, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"predict_costs\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, predictCostPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(predictCostType, predictCostMapping, append(wl, predictCostPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update predict_costs row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for predict_costs")
	}

	if !cached {
		predictCostUpdateCacheMut.Lock()
		predictCostUpdateCache[key] = cache
		predictCostUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q predictCostQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q predictCostQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for predict_costs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for predict_costs")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o PredictCostSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PredictCostSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), predictCostPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"predict_costs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, predictCostPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in predictCost slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all predictCost")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *PredictCost) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PredictCost) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no predict_costs provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(predictCostColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	predictCostUpsertCacheMut.RLock()
	cache, cached := predictCostUpsertCache[key]
	predictCostUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			predictCostAllColumns,
			predictCostColumnsWithDefault,
			predictCostColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			predictCostAllColumns,
			predictCostPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert predict_costs, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(predictCostPrimaryKeyColumns))
			copy(conflict, predictCostPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"predict_costs\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(predictCostType, predictCostMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(predictCostType, predictCostMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert predict_costs")
	}

	if !cached {
		predictCostUpsertCacheMut.Lock()
		predictCostUpsertCache[key] = cache
		predictCostUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single PredictCost record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *PredictCost) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single PredictCost record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PredictCost) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no PredictCost provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), predictCostPrimaryKeyMapping)
	sql := "DELETE FROM \"predict_costs\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from predict_costs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for predict_costs")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q predictCostQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q predictCostQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no predictCostQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from predict_costs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for predict_costs")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o PredictCostSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PredictCostSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(predictCostBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), predictCostPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"predict_costs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, predictCostPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from predictCost slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for predict_costs")
	}

	if len(predictCostAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *PredictCost) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no PredictCost provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PredictCost) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPredictCost(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PredictCostSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty PredictCostSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PredictCostSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PredictCostSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), predictCostPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"predict_costs\".* FROM \"predict_costs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, predictCostPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PredictCostSlice")
	}

	*o = slice

	return nil
}

// PredictCostExistsG checks if the PredictCost row exists.
func PredictCostExistsG(ctx context.Context, iD int) (bool, error) {
	return PredictCostExists(ctx, boil.GetContextDB(), iD)
}

// PredictCostExists checks if the PredictCost row exists.
func PredictCostExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"predict_costs\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if predict_costs exists")
	}

	return exists, nil
}

// Exists checks if the PredictCost row exists.
func (o *PredictCost) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PredictCostExists(ctx, exec, o.ID)
}
