// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AccountTypes                string
	Accounts                    string
	Articles                    string
	Categories                  string
	Credits                     string
	Debits                      string
	Entries                     string
	Incomes                     string
	Items                       string
	MaximumMonthlyPayments      string
	MonthlyPaymentItemSnapshots string
	MonthlyPaymentSnapshots     string
	PaymentTypes                string
	Payments                    string
	PredictCosts                string
	SchemaMigrations            string
	Statuses                    string
	Todos                       string
	Transactions                string
	Users                       string
}{
	AccountTypes:                "account_types",
	Accounts:                    "accounts",
	Articles:                    "articles",
	Categories:                  "categories",
	Credits:                     "credits",
	Debits:                      "debits",
	Entries:                     "entries",
	Incomes:                     "incomes",
	Items:                       "items",
	MaximumMonthlyPayments:      "maximum_monthly_payments",
	MonthlyPaymentItemSnapshots: "monthly_payment_item_snapshots",
	MonthlyPaymentSnapshots:     "monthly_payment_snapshots",
	PaymentTypes:                "payment_types",
	Payments:                    "payments",
	PredictCosts:                "predict_costs",
	SchemaMigrations:            "schema_migrations",
	Statuses:                    "statuses",
	Todos:                       "todos",
	Transactions:                "transactions",
	Users:                       "users",
}
